upstream nbp {
    server unix:/run/nbp.sock;
}

server {
    server_name nbp.exacmple.com;

    gzip on;
    gzip_types text/plain text/css application/json;

    location / {
        proxy_pass http://nbp;
        proxy_read_timeout 90s;
    }

    listen 80;
}

